const GENRES=['Isekai','Fantasy','Action','Adventure','Romance','Comedy','Horror','Mystery','School','Villainess','Cultivation','Sci-Fi','Reincarnation','Game/System','Dungeon','Demon Lord','Slice of Life','Supernatural','Sports','Mecha','Magical Girl','Post-Apocalypse','Cyberpunk','Historical','Military','Cooking','Otome','Time Travel','Survival','Political Intrigue','Music','Western','Pirates','Steampunk','Urban Fantasy','Dark Fantasy'];
const TROPES=['Overpowered Protagonist','Weak-to-Strong','Accidental Hero','Villainess Reincarnation','Deadpan Genius','Hot-Blooded Rival','Chaotic Best Friend','Mysterious Transfer Student','Ancient Sealed Power','Hidden Royalty','Fake Weakness','System Window Addict','Dense Romantic Lead','Tsundere Rival','Unreasonably Hungry Hero','Mentor Who Knows Too Much','Comic Relief Who Saves Everyone','Secret Final Boss','Prophecy That Makes No Sense','Nobody Reads The Instructions'];
const box=id=>document.getElementById(id);let selectedGenres=['Isekai','Comedy'],selectedTropes=['Overpowered Protagonist','Chaotic Best Friend','Prophecy That Makes No Sense'];
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function updateUI(){box('genreCount').textContent=selectedGenres.length+' SELECTED';box('tropeCount').textContent=selectedTropes.length+' SELECTED';const p=Number(box('parody').value),c=Number(box('chapters').value);box('parodyOut').value=p+'%';box('chapterOut').value=c;box('wordEstimate').textContent=(c*800).toLocaleString()+' words';box('configSummary').textContent=selectedGenres.length+' genres · '+selectedTropes.length+' tropes · '+p+'% parody'}
function cards(list,target,selected){target.innerHTML='';list.forEach(x=>{const e=document.createElement('button');e.type='button';e.className='select-card'+(selected.includes(x)?' active':'');e.textContent=x;e.setAttribute('aria-pressed',selected.includes(x));e.onclick=()=>{if(selected.includes(x))selected.splice(selected.indexOf(x),1);else selected.push(x);e.classList.toggle('active');e.setAttribute('aria-pressed',selected.includes(x));updateUI()};target.appendChild(e)})}
cards(GENRES,box('genres'),selectedGenres);cards(TROPES,box('tropes'),selectedTropes);
box('allGenres').onclick=()=>{selectedGenres=selectedGenres.length===GENRES.length?[]:[...GENRES];cards(GENRES,box('genres'),selectedGenres)};
box('allTropes').onclick=()=>{selectedTropes=selectedTropes.length===TROPES.length?[]:[...TROPES];cards(TROPES,box('tropes'),selectedTropes);updateUI()};
box('randomGenres').onclick=()=>{selectedGenres=shuffle(GENRES).slice(0,3);cards(GENRES,box('genres'),selectedGenres);updateUI()};
box('randomTropes').onclick=()=>{selectedTropes=shuffle(TROPES).slice(0,4);cards(TROPES,box('tropes'),selectedTropes);updateUI()};
box('resetFactory').onclick=()=>{selectedGenres=['Isekai','Comedy'];selectedTropes=['Overpowered Protagonist','Chaotic Best Friend','Prophecy That Makes No Sense'];box('parody').value=90;box('chapters').value=200;box('title').value='';box('blueprintView').innerHTML='';box('status').textContent='Configuration reset.';cards(GENRES,box('genres'),selectedGenres);cards(TROPES,box('tropes'),selectedTropes);updateUI()};
box('parody').oninput=e=>box('parodyOut').value=e.target.value+'%';
box('chapters').oninput=e=>box('chapterOut').value=e.target.value;
const WASM_BASE64='AGFzbQEAAAABCQJgAAF/YAF/AAMDAgABBgkBfwFBlZrvOgsHGQIKcmFuZG9tX3UzMgAACHNldF9zZWVkAAEKHQIUACMAQY3MZWxB3+a74wNqJAAjAAsGACAAJAAL';
let wasm=null;
async function initWasm(){if(wasm)return wasm;try{const bytes=Uint8Array.from(atob(WASM_BASE64),c=>c.charCodeAt(0));wasm=(await WebAssembly.instantiate(bytes)).instance.exports;wasm.set_seed((Date.now()^0x51f15e)&0xffffffff);return wasm}catch(e){return null}}
function rnd(){return wasm?((wasm.random_u32()>>>0)/4294967296):Math.random()}
function pick(a){return a[Math.floor(rnd()*a.length)]}
function seedText(){return (selectedGenres.join(',')+selectedTropes.join(',')+Date.now()).length}
function makeTitle(){return pick(['I Was Reincarnated With '+pick(TROPES),'The '+pick(GENRES)+' Hero Who Took Everything Too Seriously','My '+pick(TROPES)+' Life Somehow Became a '+pick(GENRES)+' Disaster','Nobody Asked for This '+pick(GENRES)+' Adventure'])}
function buildBlueprint(){const title=box('title').value.trim()||makeTitle();const chars=[{role:'PROTAGONIST',name:pick(['Alden','Mira','Rin','Kael','Liora','Yuki','Sora','Vera']),trope:pick(selectedTropes.length?selectedTropes:TROPES)},{role:'RIVAL',name:pick(['Bram','Noel','Iris','Gideon','Kael','Mira']),trope:pick(selectedTropes.length?selectedTropes:TROPES)},{role:'COMPANION',name:pick(['Sora','Vera','Rin','Yuki','Liora','Alden']),trope:pick(selectedTropes.length?selectedTropes:TROPES)}];return{title,genres:selectedGenres.length?selectedGenres:['Random'],tropes:selectedTropes.length?selectedTropes:['Random Chaos'],parody:Number(box('parody').value),chapters:Number(box('chapters').value),characters:chars,locations:['The Capital of Extremely Reasonable Laws','The Infinite Dungeon','The Market of Questionable Discounts'],hooks:['Why was the prophecy written on a receipt?','Who keeps assigning these side quests?','What is hidden beneath the most boring building in town?']}}
function renderBlueprint(bp){const root=box('blueprintView');root.innerHTML='<div class="blueprint glass-panel"><div class="blueprint-top"><div><p class="eyebrow">BLUEPRINT READY · BLSSNVJ21</p><h2>'+esc(bp.title)+'</h2></div><span class="status-pill">READY</span></div><div class="bp-stats"><div><b>'+bp.chapters+'</b><span>CHAPTERS</span></div><div><b>'+bp.parody+'%</b><span>PARODY</span></div><div><b>'+bp.genres.length+'</b><span>GENRES</span></div><div><b>'+bp.tropes.length+'</b><span>TROPES</span></div></div><div class="bp-section"><h3>GENRES</h3><div class="tag-list">'+bp.genres.map(esc).map(x=>'<span>'+x+'</span>').join('')+'</div></div><div class="bp-section"><h3>CHARACTERS</h3><div class="character-grid">'+bp.characters.map(c=>'<article><small>'+c.role+'</small><strong>'+esc(c.name)+'</strong><p>'+esc(c.trope)+'</p></article>').join('')+'</div></div><div class="bp-section"><h3>LOCATIONS & STORY HOOKS</h3><p>'+bp.locations.map(esc).join(' · ')+'</p><ul>'+bp.hooks.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></div><div class="bp-actions"><button class="button big" id="generate">GENERATE CHAPTERS <span>TURN BLUEPRINT INTO MANUSCRIPT →</span></button><button class="button ghost" id="discard">DISCARD BLUEPRINT</button></div><p id="genStatus"></p></div>';
box('generate').onclick=()=>generate(bp);box('discard').onclick=()=>{root.innerHTML='';box('status').textContent='Blueprint discarded.'}}
box('blueprint').onclick=async()=>{box('status').textContent='Consulting the original WASM random engine...';await initWasm();const bp=buildBlueprint();renderBlueprint(bp);box('status').textContent='Blueprint complete. Review it before generating chapters.'};
async function generate(bp){const s=box('genStatus'),n=bp.chapters;const novel={id:crypto.randomUUID(),...bp,created:Date.now(),position:0,generated:[]};s.textContent='Generating chapter 1 / '+n+'...';for(let i=1;i<=n;i++){novel.generated.push(makeChapter(i,bp));if(i%10===0){s.textContent='Forging chapter '+i+' / '+n+'...';await new Promise(r=>setTimeout(r,0))}}await saveNovel(novel);location.href='reader.html?id='+novel.id}
function makeChapter(i,bp){const genre=pick(bp.genres),trope=pick(bp.tropes),char=pick(bp.characters),titles=['The Problem Begins','A Completely Necessary Detour','The Power Nobody Asked For','The Villain Explains Everything','The Receipt Knows Too Much','A Duel, Somehow','The System Has Terms and Conditions','The Most Unnecessary Revelation Ever'];const jokes=['The protagonist made a heroic decision: postpone it until tomorrow.','Everyone agreed this was a terrible plan, then immediately followed it.','A dramatic silence occurred because nobody knew what to say.','The prophecy remained suspiciously confident.'];const serious='The '+genre+' situation around '+char.name+' became impossible to ignore. '+char.name+' relied on the '+trope+' instinct that had somehow carried them this far.';const comic=pick(jokes);const text=(serious+' '+comic+' '+pick(bp.hooks)+' '+serious+' '+comic+' '+pick(jokes)+' ').repeat(60);return{number:i,title:'Chapter '+i+': '+pick(titles),text:text.split(/\s+/).slice(0,800).join(' ')}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}