const LIBRARY_VERSION='14.0';
const selectedIds=new Set();
let novels=[],filtered=[];
const libraryBus=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('lnpf-library'):null;libraryBus?.addEventListener('message',async()=>{try{novels=await getNovels();render()}catch{}});const root=document.getElementById('library'),search=document.getElementById('librarySearch'),filter=document.getElementById('genreFilter'),sorter=document.getElementById('sortLibrary'),favoriteFilter=document.getElementById('favoriteFilter');
async function init(){try{novels=await getNovels();[...new Set(novels.flatMap(n=>n.genres||[]))].sort().forEach(g=>{const o=document.createElement('option');o.value=g;o.textContent=g;filter.appendChild(o)});search.oninput=render;filter.onchange=render;sorter.onchange=render;if(favoriteFilter)favoriteFilter.onchange=render;document.getElementById('exportLibrary').onclick=exportBackup;document.getElementById('importLibrary').onclick=importBackup;document.getElementById('auditLibrary').onclick=auditLibrary;document.getElementById('clearLibrary').onclick=clearLibrary;document.getElementById('selectAllLibrary').onclick=toggleSelectAll;document.getElementById('exportSelected').onclick=exportSelected;document.getElementById('deleteSelected').onclick=deleteSelected;document.getElementById('favoriteSelected').onclick=favoriteSelected;document.getElementById('storageHealth').onclick=storageHealth;render()}catch(e){root.innerHTML='<div class="empty-library"><h2>Library storage unavailable</h2><p>'+escapeHTML(e.message)+'</p></div>'}}
async function exportBackup(){try{const full=await Promise.all(novels.map(n=>getNovel(n.id)));const payload={format:'LNPF-BACKUP',version:5,schema:'chapter-sharded',exported:Date.now(),author:'BLLSNVJ21',novels:full.filter(Boolean)};const b=new Blob([JSON.stringify(payload)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='light-novel-parody-factory-backup-v5.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){alert('Export failed: '+e.message)}}
async function importBackup(){const input=document.createElement('input');input.type='file';input.accept='application/json,.json';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text()),items=Array.isArray(data)?data:data.novels;if(!Array.isArray(items))throw new Error('No novels found in this backup.');const clean=items.filter(n=>validateNovel(n).ok);if(!clean.length)throw new Error('No valid 800-word novel data found in this backup.');const imported=await importNovels(clean);novels=await getNovels();render();alert('Imported '+imported+' novel(s).')}catch(e){alert('Import failed: '+e.message)}};input.click()}
async function clearLibrary(){if(!novels.length)return;if(!confirm('Delete every locally stored novel? This cannot be undone unless you have an exported backup.'))return;await clearNovels();novels=[];render()}
function novelTotal(n){return Math.max(1,Number(n.chapterCount||n.chapters||n.generated?.length||1))}
function novelGenerated(n){return Number(n.generated?.length??n.chapterCount??0)}
function novelProgress(n){const total=novelTotal(n),pos=Math.min(Number(n.position||0),total-1);return{total,pos,pct:total<=1?100:Math.round(pos/(total-1)*100)}}
function syncSelectionUI(){const visible=new Set(filtered.map(n=>n.id));[...selectedIds].forEach(id=>{if(!visible.has(id))selectedIds.delete(id)});const c=document.getElementById('selectedCount'),ex=document.getElementById('exportSelected'),del=document.getElementById('deleteSelected'),fav=document.getElementById('favoriteSelected');if(c)c.textContent=selectedIds.size+' SELECTED';if(ex)ex.disabled=!selectedIds.size;if(del)del.disabled=!selectedIds.size;if(fav)fav.disabled=!selectedIds.size;const sa=document.getElementById('selectAllLibrary');if(sa)sa.textContent=filtered.length&&filtered.every(n=>selectedIds.has(n.id))?'CLEAR SELECTION':'SELECT ALL'}
function toggleSelectAll(){const all=filtered.length&&filtered.every(n=>selectedIds.has(n.id));filtered.forEach(n=>all?selectedIds.delete(n.id):selectedIds.add(n.id));render()}
async function exportSelected(){const items=novels.filter(n=>selectedIds.has(n.id));if(!items.length)return;try{const full=await Promise.all(items.map(n=>getNovel(n.id)));const payload={format:'LNPF-BACKUP',version:5,schema:'chapter-sharded',exported:Date.now(),author:'BLLSNVJ21',novels:full.filter(Boolean)};const blob=new Blob([JSON.stringify(payload)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='light-novel-parody-factory-selected-v4.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){alert('Selected export failed: '+e.message)}}
async function deleteSelected(){const items=novels.filter(n=>selectedIds.has(n.id));if(!items.length)return;if(!confirm('Delete '+items.length+' selected novel(s) from this browser?'))return;try{for(const n of items){await deleteNovel(n.id);localStorage.removeItem('lnpf-fav-'+n.id);selectedIds.delete(n.id)}novels=novels.filter(n=>!items.some(x=>x.id===n.id));render()}catch(e){alert('Selected delete failed: '+e.message)}}
function render(){const q=search.value.trim().toLowerCase(),g=filter.value,ff=favoriteFilter?.value||'';filtered=novels.filter(n=>(!q||JSON.stringify({title:n.title,genres:n.genres,tropes:n.tropes,characters:n.characters}).toLowerCase().includes(q))&&(!g||(n.genres||[]).includes(g))&&(!ff||(ff==='favorites'?localStorage.getItem('lnpf-fav-'+n.id)==='1':Boolean(n.checkpoint&&novelGenerated(n)<Number(n.chapters||0)))));filtered.sort((a,b)=>sorter.value==='oldest'?a.created-b.created:sorter.value==='title'?String(a.title).localeCompare(String(b.title)):sorter.value==='progress'?(b.position||0)/(novelTotal(b)-1||1)-(a.position||0)/(novelTotal(a)-1||1):sorter.value==='recent'?(Number(b.updated||b.created||0)-Number(a.updated||a.created||0)):sorter.value==='chapters'?(novelGenerated(b)-novelGenerated(a)):b.created-a.created);root.innerHTML='';document.getElementById('libraryCount').textContent=filtered.length+' / '+novels.length+' NOVELS';const totalWords=novels.reduce((s,n)=>s+(n.stats?.words||novelGenerated(n)*800),0),totalChapters=novels.reduce((s,n)=>s+novelGenerated(n),0),complete=novels.filter(n=>novelGenerated(n)>=Number(n.chapters||0)).length;document.getElementById('libraryWords').textContent=totalWords.toLocaleString()+' WORDS · '+totalChapters.toLocaleString()+' CHAPTERS · '+complete+' COMPLETE';syncSelectionUI();if(!filtered.length){root.innerHTML='<div class="empty-library"><div>▤</div><h2>No novels found</h2><p>Build something gloriously unnecessary.</p><a class="button" href="create.html">OPEN FACTORY</a></div>';return}
filtered.forEach((n,i)=>{const {total,pos,pct}=novelProgress(n),selected=selectedIds.has(n.id),fav=localStorage.getItem('lnpf-fav-'+n.id)==='1',generated=novelGenerated(n),d=document.createElement('article');d.className='book-card';d.innerHTML='<div class="book-index"><input class="book-select" type="checkbox" aria-label="Select novel" '+(selected?'checked':'')+'><span>'+String(i+1).padStart(2,'0')+'</span></div><div class="book-main"><p class="eyebrow">'+(n.genres||[]).slice(0,3).map(escapeHTML).join(' · ')+'</p><h2>'+escapeHTML(n.title)+' <button class="favorite" aria-label="Favorite novel">'+(fav?'★':'☆')+'</button></h2><p class="book-meta">'+n.chapters+' chapters · '+n.parody+'% parody · AUTHOR '+escapeHTML(n.author||'BLLSNVJ21')+' · '+(n.stats?.words||generated*800).toLocaleString()+' words · ENGINE '+escapeHTML(n.engine?.version||'legacy')+' · '+generated+'/'+n.chapters+' GENERATED</p><div class="progress-track"><span style="width:'+pct+'%"></span></div><small>'+pct+'% READ · '+(pos+1)+' / '+total+'</small></div><div class="book-actions"><a class="button" href="reader.html?id='+encodeURIComponent(n.id)+'"><strong>'+(pct?'CONTINUE':'READ')+'</strong><span>Chapter '+Math.min(pos+1,total)+'</span></a><button class="duplicate-button">DUPLICATE</button><button class="danger-button">DELETE</button></div>';if(n.checkpoint&&generated<Number(n.chapters||0)){const resume=document.createElement('a');resume.className='button';resume.href='create.html?resume='+encodeURIComponent(n.id);resume.innerHTML='<strong>RESUME</strong><span>GENERATION</span>';d.querySelector('.book-actions').prepend(resume)}d.querySelector('.book-select').onchange=()=>{selectedIds.has(n.id)?selectedIds.delete(n.id):selectedIds.add(n.id);syncSelectionUI();d.classList.toggle('selected',selectedIds.has(n.id))};d.querySelector('.favorite').onclick=()=>{localStorage.setItem('lnpf-fav-'+n.id,fav?'0':'1');render()};d.querySelector('.duplicate-button').onclick=async()=>{try{const full=await getNovel(n.id);if(!full)return;const copy=JSON.parse(JSON.stringify(full));copy.id=crypto.randomUUID();copy.title=n.title+' — Copy';copy.created=Date.now();copy.position=0;await saveNovel(copy);novels=await getNovels();render()}catch(e){alert('Duplicate failed: '+e.message)}};d.querySelector('.danger-button').onclick=async()=>{if(confirm('Delete this novel from this browser?')){await deleteNovel(n.id);localStorage.removeItem('lnpf-fav-'+n.id);novels=novels.filter(x=>x.id!==n.id);render()}};root.appendChild(d)})}
function escapeHTML(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
init();
if(libraryBus)libraryBus.onmessage=async e=>{if(['saved','deleted','cleared'].includes(e.data?.type)){try{novels=await getNovels();render()}catch{}}};
window.addEventListener('storage',e=>{if(e.key==='lnpf-library-refresh')init()});

async function auditLibrary(){if(!novels.length){alert('Library is empty.');return}const report=[];for(const n of novels){const list=await getChapterList(n.id);let bad=0,dup=0,prev=new Set();for(let i=0;i<list.length;i++){const c=await getChapter(n.id,i);if(!c||!String(c.text||'').trim())bad++;const sig=String(c?.text||'').toLowerCase().replace(/\\W+/g,' ').split(/\\s+/).filter(x=>x.length>5).slice(0,80).join(' ');if(sig&&prev.has(sig))dup++;prev.add(sig)}const expected=Number(n.chapters||n.chapterCount||0);if(list.length!==expected)bad+=Math.abs(expected-list.length);report.push(n.title+': '+list.length+'/'+expected+' chapters · '+bad+' integrity issue(s)'+(dup?' · '+dup+' repeated opening(s)':''))}const blob=new Blob(['LIGHT NOVEL PARODY FACTORY — LIBRARY AUDIT\\n\\n'+report.join('\\n')],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='lnpf-library-audit-'+Date.now()+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);alert('Audit complete. A report was downloaded.')}

async function favoriteSelected(){const items=novels.filter(n=>selectedIds.has(n.id));if(!items.length)return;items.forEach(n=>localStorage.setItem('lnpf-fav-'+n.id,'1'));render()}
async function storageHealth(){try{const s=await estimateLibraryStorage();const stats=await getLibraryStats();if(!s){alert('Storage estimate is not available in this browser.\n\nLibrary: '+stats.novels+' novels · '+stats.chapters+' chapters · '+stats.words.toLocaleString()+' words');return}const mb=x=>(x/1048576).toFixed(1);let advice=s.percent>=95?'CRITICAL: export a backup and free browser storage now.':s.percent>=85?'HIGH USAGE: consider exporting a backup.':s.percent>=70?'MODERATE USAGE: keep a backup of important novels.':'Storage level is healthy.';alert('STORAGE HEALTH\n\nUsed: '+mb(s.usage)+' MB\nQuota: '+mb(s.quota)+' MB\nUsage: '+s.percent+'%\n\n'+stats.novels+' novels · '+stats.chapters+' chapters · '+stats.words.toLocaleString()+' words\n\n'+advice)}catch(e){alert('Storage health check failed: '+e.message)}}
