const LIBRARY_VERSION='13.0';
const selectedIds=new Set();
let novels=[],filtered=[];
const libraryBus=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('lnpf-library'):null;const root=document.getElementById('library'),search=document.getElementById('librarySearch'),filter=document.getElementById('genreFilter'),sorter=document.getElementById('sortLibrary'),favoriteFilter=document.getElementById('favoriteFilter');
async function init(){try{novels=await getNovels();[...new Set(novels.flatMap(n=>n.genres||[]))].sort().forEach(g=>{const o=document.createElement('option');o.value=g;o.textContent=g;filter.appendChild(o)});search.oninput=render;filter.onchange=render;sorter.onchange=render;if(favoriteFilter)favoriteFilter.onchange=render;document.getElementById('exportLibrary').onclick=exportBackup;document.getElementById('importLibrary').onclick=importBackup;document.getElementById('clearLibrary').onclick=clearLibrary;document.getElementById('selectAllLibrary').onclick=toggleSelectAll;document.getElementById('exportSelected').onclick=exportSelected;document.getElementById('deleteSelected').onclick=deleteSelected;render()}catch(e){root.innerHTML='<div class="empty-library"><h2>Library storage unavailable</h2><p>'+escapeHTML(e.message)+'</p></div>'}}
async function exportBackup(){try{const full=await Promise.all(novels.map(n=>getNovel(n.id)));const payload={format:'LNPF-BACKUP',version:3,schema:'chapter-sharded',exported:Date.now(),author:'BLLSNVJ21',novels:full.filter(Boolean)};const b=new Blob([JSON.stringify(payload)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='light-novel-parody-factory-backup-v3.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){alert('Export failed: '+e.message)}}
async function importBackup(){const input=document.createElement('input');input.type='file';input.accept='application/json,.json';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text()),items=Array.isArray(data)?data:data.novels;if(!Array.isArray(items))throw new Error('No novels found in this backup.');const clean=items.filter(n=>n&&typeof n.id==='string'&&typeof n.title==='string'&&Array.isArray(n.generated));if(!clean.length)throw new Error('No valid chapter data found in this backup.');const imported=await importNovels(clean);novels=await getNovels();render();alert('Imported '+imported+' novel(s).')}catch(e){alert('Import failed: '+e.message)}};input.click()}
async function clearLibrary(){if(!novels.length)return;if(!confirm('Delete every locally stored novel? This cannot be undone unless you have an exported backup.'))return;await clearNovels();novels=[];render()}
function novelTotal(n){return Math.max(1,Number(n.chapterCount||n.chapters||n.generated?.length||1))}
function novelGenerated(n){return Number(n.generated?.length??n.chapterCount??0)}
function novelProgress(n){const total=novelTotal(n),pos=Math.min(Number(n.position||0),total-1);return{total,pos,pct:total<=1?100:Math.round(pos/(total-1)*100)}}
function syncSelectionUI(){const visible=new Set(filtered.map(n=>n.id));[...selectedIds].forEach(id=>{if(!visible.has(id))selectedIds.delete(id)});const c=document.getElementById('selectedCount'),ex=document.getElementById('exportSelected'),del=document.getElementById('deleteSelected');if(c)c.textContent=selectedIds.size+' SELECTED';if(ex)ex.disabled=!selectedIds.size;if(del)del.disabled=!selectedIds.size;const sa=document.getElementById('selectAllLibrary');if(sa)sa.textContent=filtered.length&&filtered.every(n=>selectedIds.has(n.id))?'CLEAR SELECTION':'SELECT ALL'}
function toggleSelectAll(){const all=filtered.length&&filtered.every(n=>selectedIds.has(n.id));filtered.forEach(n=>all?selectedIds.delete(n.id):selectedIds.add(n.id));render()}
async function exportSelected(){const items=novels.filter(n=>selectedIds.has(n.id));if(!items.length)return;try{const full=await Promise.all(items.map(n=>getNovel(n.id)));const payload={format:'LNPF-BACKUP',version:4,schema:'chapter-sharded',exported:Date.now(),author:'BLLSNVJ21',novels:full.filter(Boolean)};const blob=new Blob([JSON.stringify(payload)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='light-novel-parody-factory-selected-v4.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){alert('Selected export failed: '+e.message)}}
async function deleteSelected(){const items=novels.filter(n=>selectedIds.has(n.id));if(!items.length)return;if(!confirm('Delete '+items.length+' selected novel(s) from this browser?'))return;try{for(const n of items){await deleteNovel(n.id);localStorage.removeItem('lnpf-fav-'+n.id);selectedIds.delete(n.id)}novels=novels.filter(n=>!items.some(x=>x.id===n.id));render()}catch(e){alert('Selected delete failed: '+e.message)}}
function render(){const q=search.value.trim().toLowerCase(),g=filter.value,ff=favoriteFilter?.value||'';filtered=novels.filter(n=>(!q||JSON.stringify({title:n.title,genres:n.genres,tropes:n.tropes,characters:n.characters}).toLowerCase().includes(q))&&(!g||(n.genres||[]).includes(g))&&(!ff||(ff==='favorites'?localStorage.getItem('lnpf-fav-'+n.id)==='1':Boolean(n.checkpoint&&novelGenerated(n)<Number(n.chapters||0)))));filtered.sort((a,b)=>sorter.value==='oldest'?a.created-b.created:sorter.value==='title'?String(a.title).localeCompare(String(b.title)):sorter.value==='progress'?(b.position||0)/(novelTotal(b)-1||1)-(a.position||0)/(novelTotal(a)-1||1):b.created-a.created);root.innerHTML='';document.getElementById('libraryCount').textContent=filtered.length+' / '+novels.length+' NOVELS';document.getElementById('libraryWords').textContent=novels.reduce((s,n)=>s+(n.stats?.words||novelGenerated(n)*800),0).toLocaleString()+' WORDS';syncSelectionUI();if(!filtered.length){root.innerHTML='<div class="empty-library"><div>▤</div><h2>No novels found</h2><p>Build something gloriously unnecessary.</p><a class="button" href="create.html">OPEN FACTORY</a></div>';return}
filtered.forEach((n,i)=>{const {total,pos,pct}=novelProgress(n),selected=selectedIds.has(n.id),fav=localStorage.getItem('lnpf-fav-'+n.id)==='1',generated=novelGenerated(n),d=document.createElement('article');d.className='book-card';d.innerHTML='<div class="book-index"><input class="book-select" type="checkbox" aria-label="Select novel" '+(selected?'checked':'')+'></div><div class="book-index">'+String(i+1).padStart(2,'0')+'</div><div class="book-main"><p class="eyebrow">'+(n.genres||[]).slice(0,3).map(escapeHTML).join(' · ')+'</p><h2>'+escapeHTML(n.title)+' <button class="favorite" aria-label="Favorite novel">'+(fav?'★':'☆')+'</button></h2><p class="book-meta">'+n.chapters+' chapters · '+n.parody+'% parody · AUTHOR '+escapeHTML(n.author||'BLLSNVJ21')+' · '+(n.stats?.words||generated*800).toLocaleString()+' words · ENGINE '+escapeHTML(n.engine?.version||'legacy')+' · '+generated+'/'+n.chapters+' GENERATED</p><div class="progress-track"><span style="width:'+pct+'%"></span></div><small>'+pct+'% READ · '+(pos+1)+' / '+total+'</small></div><div class="book-actions"><a class="button" href="reader.html?id='+encodeURIComponent(n.id)+'"><strong>'+(pct?'CONTINUE':'READ')+'</strong><span>Chapter '+Math.min(pos+1,total)+'</span></a><button class="duplicate-button">DUPLICATE</button><button class="danger-button">DELETE</button></div>';if(n.checkpoint&&generated<Number(n.chapters||0)){const resume=document.createElement('a');resume.className='button';resume.href='create.html?resume='+encodeURIComponent(n.id);resume.innerHTML='<strong>RESUME</strong><span>GENERATION</span>';d.querySelector('.book-actions').prepend(resume)}d.querySelector('.book-select').onchange=()=>{selectedIds.has(n.id)?selectedIds.delete(n.id):selectedIds.add(n.id);syncSelectionUI();d.classList.toggle('selected',selectedIds.has(n.id))};d.querySelector('.favorite').onclick=()=>{localStorage.setItem('lnpf-fav-'+n.id,fav?'0':'1');render()};d.querySelector('.duplicate-button').onclick=async()=>{try{const full=await getNovel(n.id);if(!full)return;const copy=JSON.parse(JSON.stringify(full));copy.id=crypto.randomUUID();copy.title=n.title+' — Copy';copy.created=Date.now();copy.position=0;await saveNovel(copy);novels=await getNovels();render()}catch(e){alert('Duplicate failed: '+e.message)}};d.querySelector('.danger-button').onclick=async()=>{if(confirm('Delete this novel from this browser?')){await deleteNovel(n.id);localStorage.removeItem('lnpf-fav-'+n.id);novels=novels.filter(x=>x.id!==n.id);render()}};root.appendChild(d)})}
function escapeHTML(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
init();
if(libraryBus)libraryBus.onmessage=async e=>{if(['saved','deleted','cleared'].includes(e.data?.type)){try{novels=await getNovels();render()}catch{}}};
window.addEventListener('storage',e=>{if(e.key==='lnpf-library-refresh')init()});
