/* IndexedDB storage — schema 4, chapter-sharded local-first persistence. */
const DB='lnpf-library-v2',DB_VERSION=4;
const STORAGE_SCHEMA=4;
const bus=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('lnpf-library'):null;
function announce(type,id){try{bus?.postMessage({type,id,at:Date.now()})}catch{}}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result,tx=r.transaction;if(!db.objectStoreNames.contains('novels'))db.createObjectStore('novels',{keyPath:'id'});if(!db.objectStoreNames.contains('chapters')){const s=db.createObjectStore('chapters',{keyPath:['novelId','index']});s.createIndex('byNovel','novelId',{unique:false})}if(!db.objectStoreNames.contains('meta'))db.createObjectStore('meta',{keyPath:'key'});if(tx){const novels=db.transaction?tx.objectStore('novels'):null;if(novels){const cursor=novels.openCursor();cursor.onsuccess=()=>{const c=cursor.result;if(!c)return;const n=c.value;if(Array.isArray(n.generated)){const generated=n.generated,clean={...n};delete clean.generated;clean.chapterCount=generated.length;generated.forEach((chapter,i)=>tx.objectStore('chapters').put({novelId:n.id,index:i,chapter}));c.update(clean)}c.continue()}}}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function migrateLegacy(){if(localStorage.getItem('lnpf-v1-migrated'))return;localStorage.setItem('lnpf-v1-migrated','1');try{const legacy=await new Promise(resolve=>{const r=indexedDB.open('lnpf-library-v1');r.onsuccess=()=>{const db=r.result;if(!db.objectStoreNames.contains('novels')){db.close();return resolve([])}const q=db.transaction('novels').objectStore('novels').getAll();q.onsuccess=()=>{const x=q.result||[];db.close();resolve(x)};q.onerror=()=>{db.close();resolve([])}};r.onerror=()=>resolve([])});for(const n of legacy)if(n&&typeof n.id==='string'&&Array.isArray(n.generated))await saveNovel(n)}catch(e){console.warn('Legacy migration skipped',e)}}
function cleanMeta(n){const meta={...n};delete meta.generated;meta.chapterCount=Array.isArray(n.generated)?n.generated.length:Number(n.chapterCount||0);meta.storageSchema=STORAGE_SCHEMA;meta.updated=Number(n.updated||Date.now());meta.formatVersion=11;return meta}
async function saveNovel(n){if(!n||typeof n.id!=='string'||!n.id)throw new Error('Invalid novel ID.');if(!Array.isArray(n.generated))throw new Error('Invalid novel chapters.');try{await migrateLegacy();const db=await openDB();const oldMeta=await new Promise((res,rej)=>{const r=db.transaction('novels').objectStore('novels').get(n.id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)});const oldCount=Number(oldMeta?.chapterCount||0),newCount=n.generated.length;await new Promise((res,rej)=>{const tx=db.transaction(['novels','chapters'],'readwrite');tx.objectStore('novels').put(cleanMeta(n));const chapters=tx.objectStore('chapters');if(newCount<oldCount)for(let i=newCount;i<oldCount;i++)chapters.delete([n.id,i]);const start=newCount<oldCount?0:Math.min(oldCount,newCount);for(let i=start;i<newCount;i++)chapters.put({novelId:n.id,index:i,chapter:n.generated[i]});tx.oncomplete=()=>{announce('saved',n.id);res()};tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error||new Error('Storage transaction aborted.'))}) ;return n}catch(e){if(e?.name==='QuotaExceededError')throw new Error('Browser storage is full. Export a backup or delete an unused novel.');throw e}}
async function getNovels(){await migrateLegacy();const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction('novels').objectStore('novels').getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function getNovelMeta(id){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction('novels').objectStore('novels').get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function getNovel(id){await migrateLegacy();const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(['novels','chapters'],'readonly'),metaReq=tx.objectStore('novels').get(id),chapterReq=tx.objectStore('chapters').index('byNovel').getAll(IDBKeyRange.only(id));let meta=null,rows=[];metaReq.onsuccess=()=>meta=metaReq.result||null;chapterReq.onsuccess=()=>rows=chapterReq.result||[];tx.oncomplete=()=>{if(!meta)return res(null);rows.sort((a,b)=>a.index-b.index);meta.generated=rows.map(x=>x.chapter);meta.chapterCount=meta.generated.length;res(meta)};tx.onerror=()=>rej(tx.error)})}
async function updateNovelMeta(id,patch){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('novels','readwrite'),s=tx.objectStore('novels'),q=s.get(id);q.onsuccess=()=>{const n=q.result;if(!n)return;delete patch.generated;delete patch.chapterCount;s.put({...n,...patch,storageSchema:3})};q.onerror=()=>rej(q.error);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function getChapterList(id){await migrateLegacy();const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction('chapters').objectStore('chapters').index('byNovel').openCursor(IDBKeyRange.only(id));const rows=[];q.onsuccess=()=>{const cur=q.result;if(!cur)return res(rows.sort((a,b)=>a.index-b.index).map(x=>({index:x.index,number:x.chapter?.number,title:x.chapter?.title,arc:x.chapter?.arc,focus:x.chapter?.focus})));rows.push(cur.value);cur.continue()};q.onerror=()=>rej(q.error)})}
async function getChapter(id,index){await migrateLegacy();const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction('chapters').objectStore('chapters').get([id,Number(index)]);r.onsuccess=()=>res(r.result?.chapter||null);r.onerror=()=>rej(r.error)})}
async function deleteNovel(id){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(['novels','chapters'],'readwrite');tx.objectStore('novels').delete(id);const q=tx.objectStore('chapters').index('byNovel').openCursor(IDBKeyRange.only(id));q.onsuccess=()=>{const c=q.result;if(!c)return;c.delete();c.continue()};tx.oncomplete=()=>{announce('deleted',id);res()};tx.onerror=()=>rej(tx.error)})}
async function importNovels(items){if(!Array.isArray(items))throw new Error('Backup must contain an array.');const seen=new Set();let imported=0;for(const n of items){if(!n||typeof n.title!=='string'||!Array.isArray(n.generated)||n.generated.length>1000)continue;let id=typeof n.id==='string'&&n.id.trim()?n.id.trim():null;if(!id||seen.has(id)){id=(crypto.randomUUID?.()||'novel-'+Date.now()+'-'+Math.random().toString(36).slice(2))}seen.add(id);const clean={...n,id,generated:n.generated.map((ch,i)=>({...ch,number:Number(ch.number||i+1)})),updated:Date.now(),formatVersion:11};await deleteNovel(id).catch(()=>{});await saveNovel(clean);imported++}if(!imported)throw new Error('No valid novels were found in this backup.');return imported}
async function clearNovels(){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(['novels','chapters'],'readwrite');tx.objectStore('novels').clear();tx.objectStore('chapters').clear();tx.oncomplete=()=>{announce('cleared','*');res()};tx.onerror=()=>rej(tx.error)})}
async function estimateLibraryStorage(){if(!navigator.storage?.estimate)return null;const e=await navigator.storage.estimate();return{usage:e.usage||0,quota:e.quota||0,percent:e.quota?Math.round((e.usage||0)/e.quota*100):0}}
